[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2117"
blue = "0x61afdf"
cyan = "0x56b6b2"
green = "0x98c369"
magenta = "0xc678cd"
red = "0xe06c65"
white = "0x828781"
yellow = "0xd19a56"

[colors.primary]
background = "0x1e2127"
dim_foreground = "0x9a9a9a"
foreground = "0xabb2bf"
# import = [
#     "~/.config/alacritty/one_dark.toml"
# ]
[env]
TERM = "xterm-256color"


[mouse]
  hide_when_typing= true

[font]
size = 20
offset.x = 0  # For letter spacing (default: 0)
offset.y = 0  # For line spacing (default: 0)
[font.normal]
family = "JetBrainsMono Nerd font"

[window]
decorations = "none"
opacity = 0.95
startup_mode = "Maximized"
blur = true
# dynamic_padding = true

[window.padding]
x = 0
y = 3

