[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

#
# [colors.bright]
# black = "#444b6a"
# blue = "#7da6ff"
# cyan = "#0db9d7"
# green = "#b9f27c"
# magenta = "#bb9af7"
# red = "#ff7a93"
# white = "#acb0d0"
# yellow = "#ff9e64"
#
# [colors.normal]
# black = "#32344a"
# blue = "#7aa2f7"
# cyan = "#449dab"
# green = "#9ece6a"
# magenta = "#ad8ee6"
# red = "#f7768e"
# white = "#c0caf5"
# yellow = "#e0af68"
#
# [colors.primary]
# background = "#171626"
# foreground = "#c0caf5"

# [colors.primary]
# background = "#1e2127"
# dim_foreground = "#919191"
# foreground = "#bec5d1"
#

[env]
TERM = "xterm-256color"


[mouse]
  hide_when_typing= true

[font]
size = 13.0
offset.x = 0  # For letter spacing (default: 0)
offset.y = 0  # For line spacing (default: 0)

[font.normal]
family = "JetBrainsMono Nerd font"
# family = "BlexMono Nerd font"
# family = "GeistMono Nerd font"
style = "Regular"

[window]
decorations = "none"
opacity = 0.95
startup_mode = "Maximized"

[scrolling]
history = 10000
# dynamic_padding = true

[window.padding]
x = 0
y = 1
