[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.primary]
background = "0x1e2127"
dim_foreground = "0x9a9a9a"
foreground = "0xabb2bf"

[cursor.style]
shape = "beam"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd font"

[window]
decorations = "none"
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 5
y = 3
